Add alignment support to TextZipper
reflex-frp/reflex-vty pull request #40
Opened 2021-02-21 17:12 UTC by pdlla

-add alignment (left/center/right) support to TextZipper.
-add basic unit tests for newly created alignment methods in TextZipper
-also includes fix from https://github.com/reflex-frp/reflex-vty/pull/38

2021-02-22 14:46 UTC, cgibbard commented on src/Data/Text/Zipper.hs
> +    -- The cursor is on top of the first character of this text
This comment got duplicated somehow... otherwise it doesn't look like this bit changed apart from whitespace, maybe drop this hunk?

2021-02-22 14:51 UTC, cgibbard commented on src/Data/Text/Zipper.hs
> +import           Control.Exception               (assert)
This kind of table formatting is annoying to edit, since adding one import will frequently result in lots of lines needing to change, I think it's better if we avoid it. It also makes it kind of hard to tell what the diff is here.

2021-02-22 14:55 UTC, cgibbard commented on src/Data/Text/Zipper.hs
> +  -> [(Text,Bool,Int)] -- (words on that line, hidden space char, offset from beginning of line)
These triples deserve a proper record datatype declaration.

2021-02-22 15:02 UTC, cgibbard commented on src/Data/Text/Zipper.hs
> +        -- if line runs over but character of splitting is whitespace then split on the whitespace
I wonder if this logic becomes any simpler if we treat each bit of whitespace as its own word, so have wordsWithWhitespace be something like `T.groupBy (\x y -> not (isSpace x || isSpace y))`

2021-02-22 15:08 UTC, cgibbard commented
Nice work! I had a few comments here and there, but it seems like a good step forward in terms of functionality. :)

2021-02-24 06:09 UTC, pdlla commented on src/Data/Text/Zipper.hs
> +        -- if line runs over but character of splitting is whitespace then split on the whitespace
Cool idea. I think treating whitespace as words might be logically more clear. I think code complexity will be about the same. If there any other changes I need to make here I'll revisit the implementation and look into this.

Note that if a new logical line happens in the middle of 5 white space characters then one gets deleted.

2021-02-24 06:25 UTC, pdlla commented on src/Data/Text/Zipper.hs
> +  -> [(Text,Bool,Int)] -- (words on that line, hidden space char, offset from beginning of line)
Great suggestion. Done.

2021-03-24 14:28 UTC, ali-abrar commented
Any idea why CI failed?

2021-03-25 03:11 UTC, pdlla commented
> Any idea why CI failed?

` ghc: could not execute: hspec-discover`

Seems CI image doesn't support hspec-discover which is a preprocessor that hspec instructs ghc to run in order to find all test files in the code. Easy enough to fix by manually calling each test of which there is only 1 right now.

2021-04-09 17:58 UTC, ali-abrar requested changes
Could you add a changelog entry?

2021-04-09 17:58 UTC, ali-abrar commented on src/Data/Text/Zipper.hs
> +Module: Potato.Data.Text.Zipper
^

2021-04-09 17:58 UTC, ali-abrar commented
Apart from the changelog and the module name, this looks ready for merge.

2021-04-09 18:03 UTC, merged

2021-04-09 18:04 UTC, ali-abrar commented
Merged. I updated the changelog on develop.

2021-04-12 00:20 UTC, pdlla commented
@ali-abrar Since it's going to be a breaking 2.0 release for reflex-vty I wanted to consolidate the interface for with/without alignment variants of the text zipper. I'll do a follow up PR to do this eventually. I assume there's no deadline to release 2.0?